#!/bin/sh

stdbuf -oL amixer events | grep --line-buffered "event value:" | while read -r line; do
    event="$(echo "$line" | cut -d "'" -f 2 -)"
    case "$event" in
    Master*)
        "$SCRIPT_ROOT/update-sound" vol
        ;;
    Capture*)
        "$SCRIPT_ROOT/update-sound" mic
        ;;
    *) ;;
    esac
done
